/*
 * Copyright (C) 2022 Sheedon.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.sheedon.rrouter.compiler;

import org.sheedon.rrouter.strategy.support.AbstractRequestStrategy;

/**
 * 基础信息
 *
 * @Author: sheedon
 * @Email: sheedonsun@163.com
 * @Date: 2021/12/7 3:19 下午
 */
public interface Contract {

    // core package
    String CORE_PACKAGE = "org.sheedon.rrouter";
    // AbstractRequestStrategy class name
    String ARS_CLASS = AbstractRequestStrategy.class.getCanonicalName();
    // object class name
    String OBJ_CLASS = Object.class.getCanonicalName();
    // Separator
    String SEPARATOR = "$$";
    // RRouter suffix
    String ROUTER = "Router";
    // real package
    String REAL = "real";
    // classNameSuffix
    String WRAPPER_SUFFIX = "Wrapper";
    // component suffix
    String COMPONENT_SUFFIX = "Component";
    // interface prefix
    String INTERFACE_PREFIX = "On";
    // interface suffix
    String INTERFACE_SUFFIX = "Listener";
    // Listener field
    String LISTENER = "listener";
    // data loaded
    String DATA_LOADED = "DataLoaded";
    // desc
    String DOC = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY RROUTER. ";
    // 点
    String POINT = ".";
    // 远程请求
    String REMOTE_REQUEST = "RemoteRequest";
    // 本地请求
    String LOCAL_REQUEST = "LocalRequest";
    // Observable
    String OBSERVABLE_RXJAVA = "io.reactivex.rxjava3.core.Observable";

}
