package org.sheedon.rrouter.compiler;

import org.sheedon.rrouter.strategy.support.AbstractRequestStrategy;

/**
 * 基础信息
 *
 * @Author: sheedon
 * @Email: sheedonsun@163.com
 * @Date: 2021/12/7 3:19 下午
 */
public interface Contract {

    // core package
    String CORE_PACKAGE = "org.sheedon.rrouter";
    // AbstractRequestStrategy class name
    String ARS_CLASS = AbstractRequestStrategy.class.getCanonicalName();
    // object class name
    String OBJ_CLASS = Object.class.getCanonicalName();
    // Separator
    String SEPARATOR = "$$";
    // RRouter suffix
    String ROUTER = "Router";
    // real package
    String REAL = "real";
    // classNameSuffix
    String WRAPPER_SUFFIX = "Wrapper";
    // component suffix
    String COMPONENT_SUFFIX = "Component";
    // interface prefix
    String INTERFACE_PREFIX = "On";
    // interface suffix
    String INTERFACE_SUFFIX = "Listener";
    // Listener field
    String LISTENER = "listener";
    // data loaded
    String DATA_LOADED = "DataLoaded";
    // desc
    String DOC = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY RROUTER. ";
    // 点
    String POINT = ".";
    // 远程请求
    String REMOTE_REQUEST = "RemoteRequest";
    // 本地请求
    String LOCAL_REQUEST = "LocalRequest";

}
